version: '3'

services:
  app:
    build:
      context: .
    ports:
    - 8080:8080
    depends_on:
      - db
    env_file:
      - ./src/main/resources/application.properties
  db:
    image: postgres:11.4-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - database_data:/var/lib/postgresql/data
volumes:
  database_data:
    driver: local